apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ack-ec2-controller
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: ec2-chart
      version: "v0.0.18"
      sourceRef:
        kind: HelmRepository
        name: ack
        namespace: flux-system
  values:
    aws:
      region: "us-east-1"
