---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: s3-controller
  namespace: flux-system
spec:
  interval: 5m0s
  url: oci://public.ecr.aws/aws-controllers-k8s/s3-chart
  ref:
    tag: latest

