---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: s3-controller
  namespace: flux-system
spec:
  interval: 5m0s
  url: oci://public.ecr.aws/aws-controllers-k8s/s3-controller
  ref:
    tag: v0.1.4
